services:
  postgres:
    image: 'postgres:16.3-alpine'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '127.0.0.1:54342:5432/tcp'
    volumes:
      - 'pg_data:/var/lib/postgresql/data:delegated'
    healthcheck:
      test: ["CMD-SHELL", "su", "postgres", "-c", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg_data:
